-- V1: 업로드 파일 메타데이터 테이블을 만듭니다.
-- 최초 DB와 기존 DB 모두 이 마이그레이션에서 생성하며, 적용 이력이 있으면 재실행하지 않습니다.
CREATE TABLE IF NOT EXISTS ATCH_FILE (
    FILE_ID VARCHAR(50) NOT NULL,
    ATCH_FILE_GRPID VARCHAR(50) NOT NULL,
    ORGNL_FILE_NM VARCHAR(255) NOT NULL,
    PHYS_FILE_NM VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SZ BIGINT NOT NULL,
    FILE_EXT VARCHAR(20),
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RGTR_ID VARCHAR(50),
    CONSTRAINT PK_ATCH_FILE PRIMARY KEY (FILE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_ATCH_FILE_GRPID ON ATCH_FILE(ATCH_FILE_GRPID);
