server.port=8080

# Encoding Settings
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html;charset=UTF-8

# 수동 Bean이 자동 Bean을 오버라이딩하도록 설정
spring.main.allow-bean-definition-overriding=true

# open-in-view(혹은 Open-Session-In-View(OSIV))
# true(기본값) : 사용자에게 응답 또는 view가 렌더링될 때까지 영속성 컨텍스트 유지
# false : 트랜잭션이 종료될 때 영속성 컨텍스트 종료
spring.jpa.open-in-view=false


# DB서버 타입(hsql,mysql,oracle,altibase,tibero) - datasource 및 sqlMap 파일 지정에 사용됨
Globals.DbType=hsql_server

#hsql(내장, 디비 접속 X)과 hsql_server는 다른 디비에 접속 가능
#Globals.hsql_server.DriverClassName=net.sf.log4jdbc.DriverSpy
Globals.hsql_server.DriverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
Globals.hsql_server.Url=jdbc:log4jdbc:hsqldb:hsql://127.0.0.1:9001/ArkiveDB
Globals.hsql_server.UserName=sa
Globals.hsql_server.Password=

# --- 시작 이후 언제나(always) sql을 읽으라는 뜻 ---
spring.sql.init.mode=always
# DDL/스키마 스크립트 파일들 (콤마로 구분하거나 * 패턴 사용) 
#spring.sql.init.schema-locations=classpath:/db/sampledb.sql
spring.sql.init.schema-locations=classpath:/db/sampledb.sql,classpath:/db/system.sql

# 로그인 인증 제한(login authentication limit)
# (사용 여부 설정값 : true, false)
Globals.login.Lock = true
# -인증 재시도 횟수
Globals.login.LockCount = 5

#EncyptionUtil 변수
Globals.PUBLIC_KEY 		= __blmsPublickey__
Globals.RSA_WEB_KEY 	= __rsaBlmsPrivateKey__
Globals.RSA_INSTANCE 	= RSA_BLMS

# 파일 업로드 경로(경로 설정은 반드시 절대경로를 사용해야함, 경로 뒤에 /를 붙여줘야 함.)운영
Globals.FILE_TEMP_PATH 	=  /serv/tomcat/blms/FILE/tempUpload
Globals.FILE_REAL_PATH 	=  /serv/tomcat/blms/FILE/realUpload
Globals.SHOW_TEMP_PATH 	=  serv/tomcat/blms/FILE/tempUpload
Globals.SHOW_REAL_PATH 	=  serv/tomcat/blms/FILE/realUpload

#Globals.FILE_TEMP_PATH 	=  /BLMS/FILE/tempUpload
#Globals.FILE_REAL_PATH 	=  /BLMS/FILE/realUpload
#Globals.SHOW_TEMP_PATH 	=  BLMS/FILE/tempUpload
#Globals.SHOW_REAL_PATH 	=  BLMS/FILE/realUpload

#썸네일 프로그램(FFMPEG) 경로
Globals.FFMPEG_PATH = /usr/bin


# 파일 확장자 화이트리스트(허용목록) : 파일 확장자를 (.)과 함께 이어서 사용하며 (.)로 시작한다.
Globals.fileUpload.Extensions.Images = .gif.jpg.jpeg.png
Globals.fileUpload.Extensions = .gif.jpg.jpeg.png.xls.xlsx
Globals.fileDownload.Extensions = .gif.jpg.jpeg.png

# for JFile properties
system.uploadpath = C:/egovframework/upload/

private.key = 1234567891011121
private.iv = 1234567891011121

#SMS API KEY
SMS.APIKEY = jozw4mljh9qk9uodq2yqjf07hmpbxx4x
SMS.ID = lee9441
SMS.URL = https://sipapis.aligo.in
#운영
#SMS.TEL = 0414177715
#개발
SMS.TEL = 0313887008

#SMS.APIKEY = s52zbfl6u7jajpxubf2yu7h8r8zxt541
#SMS.ID = ghevaluation
#SMS.URL = https://sipapis.aligo.in
#SMS.TEL = 031-220-3513

#nice.clientID = f4b2db7b-4ce2-4a93-badc-43a1e1bc84ea
#nice.secretKey = c9ed1c8af942ed764faace874bf8ea2e4b02e6
#nice.accessToken = 1fdc43cb-aae5-4feb-9051-b156d4906df7



#프론트엔드 백엔드가 있을시 Origin(url)에서 오는 요청은 허용 하기위해 필요
# Access-Control-Allow-Origin
Globals.Allow.Origin = http://localhost:3000

#암호화서비스 알고리즘 키
#주의 : 반드시 기본값 "egovframe"을 다른것으로 변경하여 사용하시기 바랍니다.
Globals.crypto.algoritm = egovframe

#JWT secret key
#주의 : 반드시 기본값을 다른것으로 변경하여 사용하시기 바랍니다
Globals.jwt.secret = my-secret-jwt-key-for-egovframe-simple-homepage-project

#swaggerdoc
springdoc.version=v4.2.0
springdoc.packages-to-scan=egovframework
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.groups.enabled=true
springdoc.cache.disabled=true

#Sns
Sns.naver.clientId=YOUR_CLIENT_ID
Sns.naver.clientSecret=YOUR_CLIENT_SECRET
Sns.naver.callbackUrl=http://localhost:3000/login/naver/callback
Sns.kakao.clientId=YOUR_CLIENT_ID
Sns.kakao.callbackUrl=http://localhost:3000/login/kakao/callback
