-- V28: 소셜 로그인 연계 테이블.
-- 소셜 계정과 내부 USER를 분리한다. 회원 매핑 정책: 연계된 USER가 있으면 세션 로그인,
-- 없으면 기존 ID 연결(비밀번호 확인) 또는 신규 USER 생성 후 연계한다.
CREATE TABLE IF NOT EXISTS OAUTH_LINK (
    PROVIDER VARCHAR(20) NOT NULL,
    PROVIDER_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    LINK_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_OAUTH_LINK PRIMARY KEY (PROVIDER, PROVIDER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OAUTH_USER ON OAUTH_LINK(USER_ID);
