-- V8: OTHER_ 그룹을 DROPZONE_으로 이전한다. OTHER_ 타입 분기 제거에 앞서 기존 행을 이전한다.
UPDATE ATCH_FILE
SET ATCH_FILE_GRPID = CONCAT('DROPZONE_', SUBSTRING(ATCH_FILE_GRPID FROM 7))
WHERE ATCH_FILE_GRPID LIKE 'OTHER_%';
